### ISSUE TITLE
Crash on start after updating BoP to build 2389

### ISSUE THREAD

**Issue by Geethebluesky** [progwml6/HungerOverhaul#187]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 2691
`Mantle: ` nope
`Natura: ` nope
`Apple Core: ` 3.1.1
`Hunger Overhaul: ` 1.3.1 build 144

## Report Information
Fruit salad is causing a crash at MC startup (doesn't get to main menu), I believe it's been removed by BoP.

    net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Hunger Overhaul (hungeroverhaul)
    Caused by: java.lang.NoSuchFieldError: saladfruit
	at iguanaman.hungeroverhaul.module.biomesoplenty.BiomesOPlentyModule.init(BiomesOPlentyModule.java:17)
	at iguanaman.hungeroverhaul.HungerOverhaul.init(HungerOverhaul.java:105)
[...]

## Steps to Reproduce
Just load both mods together.

## Crash Log
[Gist](https://gist.github.com/Geethebluesky/4bb858f3c937b1771be9fed7f36b4088)

## Forge Log
[latest.log](https://gist.github.com/Geethebluesky/e628c7870db6eb2d167b5372a83d8330)

**Comment by Geethebluesky** [comment]
Nevermindddddddddddddddddd I wasn't subscribed to Curseforge updates for HO so I didn't see there was a build 146 which solves this.
